-- MySQL Script generated by MySQL Workbench
-- Tue May 15 03:30:12 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sisgec
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sisgec
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sisgec` DEFAULT CHARACTER SET utf8 ;
USE `sisgec` ;

-- -----------------------------------------------------
-- Table `sisgec`.`addresses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sisgec`.`addresses` ;

CREATE TABLE IF NOT EXISTS `sisgec`.`addresses` (
  `id` INT(4) UNSIGNED NOT NULL AUTO_INCREMENT,
  `street` VARCHAR(45) NULL,
  `exterior_number` VARCHAR(5) NULL,
  `interior_number` VARCHAR(6) NULL,
  `postal_code` VARCHAR(6) NULL,
  `colony` VARCHAR(35) NULL,
  `city` VARCHAR(35) NULL,
  `state` VARCHAR(31) NULL,
  `country` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sisgec`.`medical_history`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sisgec`.`medical_history` ;

CREATE TABLE IF NOT EXISTS `sisgec`.`medical_history` (
  `id` INT(4) NOT NULL AUTO_INCREMENT,
  `updated_date` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_date` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sisgec`.`patients`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sisgec`.`patients` ;

CREATE TABLE IF NOT EXISTS `sisgec`.`patients` (
  `id` INT(4) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `lastname` VARCHAR(55) NULL,
  `birthdate` DATE NULL,
  `gender` CHAR(1) NULL,
  `address_id` INT(4) UNSIGNED NOT NULL,
  `origin` VARCHAR(45) NULL,
  `reside` VARCHAR(45) NULL,
  `phone` VARCHAR(20) NULL,
  `religion` VARCHAR(45) NULL,
  `scholarship` VARCHAR(45) NULL,
  `email` VARCHAR(80) NULL,
  `medical_history_id` INT(4) NULL,
  `updated_date` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_date` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`, `address_id`, `medical_history_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_Pacientes_Direcciones_idx` (`address_id` ASC),
  UNIQUE INDEX `Email_UNIQUE` (`email` ASC),
  UNIQUE INDEX `Historial_Clinico_Id_UNIQUE` (`medical_history_id` ASC),
  CONSTRAINT `fk_Pacientes_Direcciones`
    FOREIGN KEY (`address_id`)
    REFERENCES `sisgec`.`addresses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pacientes_Historial_Clinico`
    FOREIGN KEY (`medical_history_id`)
    REFERENCES `sisgec`.`medical_history` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sisgec`.`records`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sisgec`.`records` ;

CREATE TABLE IF NOT EXISTS `sisgec`.`records` (
  `id` INT(4) NOT NULL,
  `name` VARCHAR(45) NULL,
  `slug` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `slug_UNIQUE` (`slug` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sisgec`.`reports`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sisgec`.`reports` ;

CREATE TABLE IF NOT EXISTS `sisgec`.`reports` (
  `id` INT(4) NOT NULL,
  `current_condition` LONGTEXT NULL,
  `diagnosis` LONGTEXT NULL,
  `treatment` LONGTEXT NULL,
  `medical_history_id` INT(4) NULL,
  `updated_date` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_date` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_reports_has_medical_history_idx` (`medical_history_id` ASC),
  CONSTRAINT `fk_reports_has_medical_history`
    FOREIGN KEY (`medical_history_id`)
    REFERENCES `sisgec`.`medical_history` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sisgec`.`reports_has_record`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sisgec`.`reports_has_record` ;

CREATE TABLE IF NOT EXISTS `sisgec`.`reports_has_record` (
  `id` INT(4) NOT NULL AUTO_INCREMENT,
  `report_id` INT(4) NOT NULL,
  `record_id` INT(4) NOT NULL,
  PRIMARY KEY (`id`, `report_id`, `record_id`),
  INDEX `fk_Reportes_has_Antecedentes_Antecedentes1_idx` (`record_id` ASC),
  INDEX `fk_Reportes_has_Antecedentes_Reportes1_idx` (`report_id` ASC),
  CONSTRAINT `fk_Reportes_has_Antecedentes_Reportes1`
    FOREIGN KEY (`report_id`)
    REFERENCES `sisgec`.`reports` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reportes_has_Antecedentes_Antecedentes1`
    FOREIGN KEY (`record_id`)
    REFERENCES `sisgec`.`records` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sisgec`.`recipes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sisgec`.`recipes` ;

CREATE TABLE IF NOT EXISTS `sisgec`.`recipes` (
  `id` INT(4) NOT NULL,
  `patient_id` INT(4) UNSIGNED NULL,
  `date` DATE NULL,
  `report_id` INT(4) NULL,
  `IDX` VARCHAR(45) NULL,
  `Folio` INT(6) UNSIGNED NULL DEFAULT 000000,
  `content` MEDIUMTEXT NULL,
  `updated_date` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_date` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `Receta Paciente_idx` (`patient_id` ASC),
  INDEX `Receta Reporte_idx` (`report_id` ASC),
  UNIQUE INDEX `Folio_UNIQUE` (`Folio` ASC),
  CONSTRAINT `Receta Paciente`
    FOREIGN KEY (`patient_id`)
    REFERENCES `sisgec`.`patients` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Receta Reporte`
    FOREIGN KEY (`report_id`)
    REFERENCES `sisgec`.`reports` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sisgec`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sisgec`.`users` ;

CREATE TABLE IF NOT EXISTS `sisgec`.`users` (
  `id` INT(4) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `lastname` VARCHAR(55) NULL,
  `email` VARCHAR(80) NULL,
  `password` VARCHAR(60) NULL,
  `type` INT(1) NULL DEFAULT 1 COMMENT '0 - Admin, 1 - Doc, 2 - Secre',
  `job` VARCHAR(65) NULL,
  `professional_license` INT(8) NULL,
  `address_id` INT(4) UNSIGNED NOT NULL,
  `updated_date` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_date` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`, `address_id`),
  UNIQUE INDEX `Ced_Prof_UNIQUE` (`professional_license` ASC),
  INDEX `Usuario - Direccion_idx` (`address_id` ASC),
  UNIQUE INDEX `address_id_UNIQUE` (`address_id` ASC),
  CONSTRAINT `User - Address`
    FOREIGN KEY (`address_id`)
    REFERENCES `sisgec`.`addresses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sisgec`.`Sistema`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sisgec`.`Sistema` ;

CREATE TABLE IF NOT EXISTS `sisgec`.`Sistema` (
  `idSistema` INT NOT NULL,
  PRIMARY KEY (`idSistema`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
